version: "3.8"

services:
  chrome:
    image: selenium/standalone-chrome:3.141.59-zirconium
    volumes:
      - /dev/shm:/dev/shm

  app:
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/rental_of_vehicles
      - bundle_path:/bundle
    environment:
      - HUB_URL=http://chrome:4444/wd/hub
      - BUNDLE_PATH=/bundle/vendor
      - BUNDLE_APP_CONFIG=/app/.bundle
    depends_on:
      - chrome

volumes:
  bundle_path:
